export const DIAGNOSTIC_CODES = {
  OPENAPI_PATHS_INVALID: 'ASF-OAS-1001',
  OPENAPI_VERSION_UNSUPPORTED: 'ASF-OAS-1002',
  OPENAPI_PARSE_FAILED: 'ASF-OAS-1003',
  OPENAPI_OPERATION_INVALID: 'ASF-OAS-1004',
  OPENAPI_COMPATIBILITY_MODE: 'ASF-OAS-2001',
  CONFIG_INVALID: 'ASF-CFG-1001',
  SOURCE_EMPTY: 'ASF-SRC-1001',
  SOURCE_TOO_LARGE: 'ASF-SRC-1002',
  CLI_USAGE: 'ASF-CLI-1001',
  CLI_INPUT: 'ASF-CLI-1002',
  INTERNAL_UNEXPECTED: 'ASF-INT-9000',
} as const

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES]
